guard 'brakeman' do
  watch(%r{^app/.+\.rb$})
  watch(%r{^app/.+\.erb$})
  watch(%r{^app/.+\.haml$})
  watch(%r{^app/.+\.rhtml$})
  watch(%r{^lib/.+\.rb$})
  watch('Gemfile')
  watch(%r{^config/.+\.rb$})
end