guard 'brakeman', :chatty => false,:notifications => true, :run_on_start => true, :min_confidence => 0 do
  watch(%r{^app/.+\.(erb|haml|rhtml|rb)$})
  watch(%r{^config/.+\.rb$})
  watch(%r{^lib/.+\.rb$})
  watch('Gemfile')
end
